services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server
    container_name: sqlserver_container
    environment:
      - SA_PASSWORD=Your_password123
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

  web:
    build:
      context: .
      dockerfile: TeamTrack.Web/Dockerfile
    container_name: web_container
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=YourDb;User Id=sa;Password=Your_password123;
    depends_on:
      - sqlserver
    volumes:
      - web_data:/app
    entrypoint: >
      /bin/sh -c "dotnet ef database update && dotnet TeamTrack.Web.dll"

volumes:
  sql_data:
  web_data:
